apt-get install --yes git
apt-get install --yes emacs
apt-get install --yes geany
apt-get install --yes mercurial
apt-get install --yes gimp
apt-get install --yes virtualbox
apt-get install --yes virtualbox-qt
apt-get install --yes virtualbox-dkms
apt-get install --yes vagrant
apt-get install --yes openvpn
apt-get install --yes network-manager-openvpn-gnome
apt-get install --yes resolvconf
apt-get install --yes openssh-server
apt-get install --yes build-essential
apt-get install --yes python-setuptools
apt-get install --yes python-virtualenv
apt-get install --yes python-dev
apt-get install --yes python-pip
apt-get install --yes python-numpy
apt-get install --yes python-scipy
apt-get install --yes python-matplotlib
apt-get install --yes irssi
apt-get install --yes ipython-notebook
apt-get install --yes p7zip
apt-get install --yes tk8.5
apt-get install --yes xchat
apt-get install --yes gparted
apt-get install --yes ttf-mscorefonts-installer
