apt install --yes git
apt install --yes emacs
apt install --yes geany
apt install --yes mercurial
apt install --yes gimp
apt install --yes build-essential
apt install --yes python-setuptools
apt install --yes python-virtualenv
apt install --yes python-dev
apt install --yes python-pip
apt install --yes python-numpy
apt install --yes python-scipy
apt install --yes python-matplotlib
apt install --yes irssi
apt install --yes ipython-notebook
apt install --yes p7zip
apt install --yes tk8.5
apt install --yes xchat
apt install --yes gparted
apt install --yes ttf-mscorefonts-installer
