apt-get install --yes emacs
apt-get install --yes git
apt-get install --yes mercurial
apt-get install --yes virtualbox
apt-get install --yes vagrant
apt-get install --yes build-essential
apt-get install --yes python-setuptools
apt-get install --yes python-virtualenv
apt-get install --yes python-dev
apt-get install --yes python-pip
apt-get install --yes p7zip
